Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
AllCops:
  NewCops: enable
